"""
================================================================================
  IEEE-CIS Fraud Detection — Exploratory Data Analysis (EDA)
================================================================================

Purpose
-------
This module performs a thorough, multi-stage EDA on the preprocessed dataset
generated by src/preprocessing.py  →  data/processed_train.csv

It produces:
  • A rich set of publication-quality plots saved to  reports/figures/
  • A plain-text summary report saved to            reports/eda_summary.txt

Why a dedicated EDA module?
---------------------------
EDA is not just "look at some graphs". Done rigorously it:
  1. Validates that our preprocessing worked correctly.
  2. Reveals class imbalance, outliers, and correlation structures that
     directly inform our modelling choices (threshold tuning, class weights,
     feature selection, etc.).
  3. Surfaces temporal / demographic fraud patterns usable as extra features.

Run
---
    python3 src/eda.py          (from project root)
"""

import os
import sys
import warnings
import textwrap

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")          # non-interactive backend — saves to file
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.ticker as mticker
import seaborn as sns

warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────────────────────
BASE_DIR    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH   = os.path.join(BASE_DIR, "data", "processed_train.csv")
FIG_DIR     = os.path.join(BASE_DIR, "reports", "figures")
REPORT_PATH = os.path.join(BASE_DIR, "reports", "eda_summary.txt")

os.makedirs(FIG_DIR, exist_ok=True)
os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# Global style
# ─────────────────────────────────────────────────────────────────────────────
PALETTE    = {"legit": "#4A90D9", "fraud": "#E74C3C"}
FRAUD_CLR  = "#E74C3C"
LEGIT_CLR  = "#4A90D9"
ACCENT_CLR = "#F39C12"
BG_CLR     = "#0F1117"
TEXT_CLR   = "#EAEAEA"
GRID_CLR   = "#2A2D3E"

plt.rcParams.update({
    "figure.facecolor":  BG_CLR,
    "axes.facecolor":    BG_CLR,
    "axes.edgecolor":    GRID_CLR,
    "axes.labelcolor":   TEXT_CLR,
    "axes.titlecolor":   TEXT_CLR,
    "xtick.color":       TEXT_CLR,
    "ytick.color":       TEXT_CLR,
    "grid.color":        GRID_CLR,
    "text.color":        TEXT_CLR,
    "legend.facecolor":  "#1A1D2E",
    "legend.edgecolor":  GRID_CLR,
    "font.family":       "sans-serif",
    "font.size":         11,
    "axes.titlesize":    14,
    "axes.labelsize":    12,
})

# ─────────────────────────────────────────────────────────────────────────────
# Utility helpers
# ─────────────────────────────────────────────────────────────────────────────
def _save(fig, name):
    path = os.path.join(FIG_DIR, name)
    fig.savefig(path, bbox_inches="tight", dpi=150, facecolor=BG_CLR)
    plt.close(fig)
    print(f"  ✔ Saved → {os.path.relpath(path, BASE_DIR)}")

def _section(title, lines, fh):
    fh.write("\n" + "=" * 72 + "\n")
    fh.write(f"  {title}\n")
    fh.write("=" * 72 + "\n")
    for line in lines:
        fh.write(line + "\n")

# ─────────────────────────────────────────────────────────────────────────────
# EDA Sections
# ─────────────────────────────────────────────────────────────────────────────

def section_01_overview(df, fh):
    """
    ### EDA Section 1 — Dataset Overview
    What: Basic shape, column types, missing values, and memory after preprocessing.
    Why : Confirms preprocessing achieved its goals (nulls reduced, dtypes compact).
    """
    print("\n[EDA 1/7] Dataset Overview...")
    lines = [
        f"Rows            : {df.shape[0]:,}",
        f"Columns         : {df.shape[1]:,}",
        f"Memory usage    : {df.memory_usage(deep=True).sum() / 1024**2:.1f} MB",
        f"Numeric cols    : {df.select_dtypes(include='number').shape[1]}",
        f"Object cols     : {df.select_dtypes(include='object').shape[1]}",
        "",
        "Remaining NaN counts (top 15 if any):",
    ]
    nan_summary = df.isnull().sum()
    nan_summary = nan_summary[nan_summary > 0].sort_values(ascending=False).head(15)
    if nan_summary.empty:
        lines.append("  → No missing values remain!")
    else:
        for col, cnt in nan_summary.items():
            lines.append(f"  {col:<35} {cnt:>8,}  ({100*cnt/len(df):.1f}%)")

    _section("1. Dataset Overview", lines, fh)
    print("     Done.")


def section_02_class_imbalance(df, fh):
    """
    ### EDA Section 2 — Class Imbalance Analysis
    What: Visualise the ratio of fraudulent vs legitimate transactions.
    Why : Fraud datasets are almost always heavily imbalanced (~3% fraud).
          Understanding the imbalance drives decisions like SMOTE, class weights,
          or precision-recall optimisation instead of raw accuracy.
    """
    print("\n[EDA 2/7] Class Imbalance...")
    counts     = df["isFraud"].value_counts()
    pct_fraud  = 100 * counts[1] / len(df)
    pct_legit  = 100 * counts[0] / len(df)

    lines = [
        f"Legitimate (0)  : {counts[0]:>9,}  ({pct_legit:.2f}%)",
        f"Fraudulent (1)  : {counts[1]:>9,}  ({pct_fraud:.2f}%)",
        f"Imbalance ratio : {counts[0]/counts[1]:.1f}:1  (legit:fraud)",
        "",
        "Implication: A naive model predicting 'legit' always scores "
        f"{pct_legit:.1f}% accuracy but catches 0% of fraud. "
        "We must use AUC-PR or F1 as our evaluation metric.",
    ]
    _section("2. Class Imbalance", lines, fh)

    # ── Plot ──────────────────────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    fig.suptitle("Class Distribution — Fraudulent vs Legitimate", fontsize=16, y=1.02)

    # Bar chart
    ax = axes[0]
    bars = ax.bar(["Legitimate", "Fraudulent"],
                  [counts[0], counts[1]],
                  color=[LEGIT_CLR, FRAUD_CLR], width=0.5, edgecolor="none")
    ax.set_title("Transaction Counts")
    ax.set_ylabel("Count")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
    for bar, cnt, pct in zip(bars, [counts[0], counts[1]], [pct_legit, pct_fraud]):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2000,
                f"{cnt:,}\n({pct:.1f}%)", ha="center", va="bottom",
                color=TEXT_CLR, fontsize=11, fontweight="bold")
    ax.set_ylim(0, counts[0] * 1.18)

    # Pie chart
    ax2 = axes[1]
    wedges, texts, autotexts = ax2.pie(
        [counts[0], counts[1]],
        labels=["Legitimate", "Fraudulent"],
        colors=[LEGIT_CLR, FRAUD_CLR],
        autopct="%1.2f%%",
        startangle=140,
        wedgeprops=dict(edgecolor=BG_CLR, linewidth=2),
        pctdistance=0.75,
    )
    for t in autotexts:
        t.set_color(TEXT_CLR); t.set_fontsize(12)
    ax2.set_title("Proportion")

    fig.tight_layout()
    _save(fig, "02_class_imbalance.png")
    print("     Done.")


def section_03_transaction_amount(df, fh):
    """
    ### EDA Section 3 — Transaction Amount Distribution
    What: Distribution of TransactionAmt split by fraud label, plus log-scale view.
    Why : Fraudulent transactions may cluster at unusual amounts (very low or
          suspiciously round high values). Log-scale exposes the long tail.
    """
    print("\n[EDA 3/7] Transaction Amount Distributions...")

    legit_amt  = df.loc[df["isFraud"] == 0, "TransactionAmt"].dropna()
    fraud_amt  = df.loc[df["isFraud"] == 1, "TransactionAmt"].dropna()

    stats_lines = []
    for label, s in [("Legitimate", legit_amt), ("Fraudulent", fraud_amt)]:
        stats_lines += [
            f"  {label}:",
            f"    Mean   {s.mean():>10.2f}    Median  {s.median():>10.2f}",
            f"    Std    {s.std():>10.2f}    Max     {s.max():>10.2f}",
            f"    25th%  {s.quantile(.25):>10.2f}    75th%   {s.quantile(.75):>10.2f}",
            "",
        ]
    _section("3. Transaction Amount Analysis", stats_lines, fh)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("Transaction Amount Distribution by Fraud Label", fontsize=16)

    # KDE — raw scale
    ax = axes[0]
    sns.kdeplot(legit_amt.clip(upper=legit_amt.quantile(0.99)),
                ax=ax, color=LEGIT_CLR, label="Legitimate", fill=True, alpha=0.35, linewidth=2)
    sns.kdeplot(fraud_amt.clip(upper=fraud_amt.quantile(0.99)),
                ax=ax, color=FRAUD_CLR, label="Fraudulent", fill=True, alpha=0.50, linewidth=2)
    ax.set_xlabel("TransactionAmt (clipped at 99th pct)")
    ax.set_ylabel("Density")
    ax.set_title("Density — Linear Scale")
    ax.legend()

    # Box plot — log scale
    ax2 = axes[1]
    plot_df = pd.DataFrame({
        "Amount": pd.concat([legit_amt, fraud_amt]),
        "Label":  ["Legitimate"] * len(legit_amt) + ["Fraudulent"] * len(fraud_amt),
    })
    sns.boxplot(data=plot_df, x="Label", y="Amount", palette=[LEGIT_CLR, FRAUD_CLR],
                ax=ax2, linewidth=1.5, flierprops=dict(marker=".", color=ACCENT_CLR,
                markersize=2, alpha=0.3))
    ax2.set_yscale("log")
    ax2.set_title("Box Plot — Log Scale")
    ax2.set_xlabel("")
    ax2.set_ylabel("TransactionAmt (log)")

    fig.tight_layout()
    _save(fig, "03_transaction_amount.png")
    print("     Done.")


def section_04_temporal_patterns(df, fh):
    """
    ### EDA Section 4 — Temporal Fraud Patterns
    What: Fraud rate by Hour-of-Day and Day-of-Week (features we engineered).
    Why : Fraudsters operate in predictable time windows (often late night,
          early week). Visualising this validates our feature extraction and
          gives the model usable cyclical signal.
    """
    print("\n[EDA 4/7] Temporal Patterns...")

    lines = ["Hour-of-Day fraud rate (top 5 riskiest hours):"]
    if "Transaction_Hour" in df.columns:
        hour_fraud = df.groupby("Transaction_Hour")["isFraud"].mean().sort_values(ascending=False)
        for h, r in hour_fraud.head(5).items():
            lines.append(f"  Hour {int(h):02d}:00  →  {r*100:.2f}% fraud rate")
    _section("4. Temporal Patterns", lines, fh)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("Temporal Fraud Patterns", fontsize=16)

    for ax, col, title, xlabel in zip(
        axes,
        ["Transaction_Hour", "Transaction_Day"],
        ["Fraud Rate by Hour of Day", "Fraud Rate by Day of Week"],
        ["Hour (0 = midnight)", "Day (0 = Mon, 6 = Sun)"],
    ):
        if col not in df.columns:
            ax.set_visible(False)
            continue
        grouped = df.groupby(col)["isFraud"].mean().reset_index()
        grouped.columns = [col, "fraud_rate"]
        bars = ax.bar(grouped[col], grouped["fraud_rate"] * 100,
                      color=FRAUD_CLR, edgecolor="none", alpha=0.85)
        ax.set_xlabel(xlabel)
        ax.set_ylabel("Fraud Rate (%)")
        ax.set_title(title)
        ax.axhline(df["isFraud"].mean() * 100, color=ACCENT_CLR,
                   linestyle="--", linewidth=1.5, label="Overall avg")
        ax.legend()

    fig.tight_layout()
    _save(fig, "04_temporal_patterns.png")
    print("     Done.")


def section_05_correlation_heatmap(df, fh):
    """
    ### EDA Section 5 — Correlation Heatmap (Top Features vs isFraud)
    What: Pearson correlation of the 25 most correlated numeric features with isFraud.
    Why : Reveals which engineered and raw features carry the most linear
          relationship with the target — a quick feature importance proxy
          before formal model training.
    """
    print("\n[EDA 5/7] Correlation Heatmap...")

    num_df = df.select_dtypes(include="number")
    corr_with_target = num_df.corr()["isFraud"].drop("isFraud").abs().sort_values(ascending=False)
    top25 = corr_with_target.head(25).index.tolist()

    lines = ["Top 10 numeric features most correlated with isFraud:"]
    for feat, val in corr_with_target.head(10).items():
        lines.append(f"  {feat:<35} |ρ| = {val:.4f}")
    _section("5. Feature Correlation with isFraud", lines, fh)

    corr_matrix = num_df[top25 + ["isFraud"]].corr()

    fig, ax = plt.subplots(figsize=(16, 13))
    mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
    sns.heatmap(
        corr_matrix,
        mask=mask,
        ax=ax,
        cmap="coolwarm",
        center=0,
        vmin=-1, vmax=1,
        linewidths=0.3,
        linecolor=BG_CLR,
        annot=len(corr_matrix) <= 20,
        fmt=".2f",
        annot_kws={"size": 7},
        cbar_kws={"shrink": 0.75, "label": "Pearson ρ"},
    )
    ax.set_title("Correlation Matrix — Top 25 Features + isFraud", fontsize=15, pad=15)
    plt.xticks(rotation=45, ha="right")
    plt.yticks(rotation=0)
    fig.tight_layout()
    _save(fig, "05_correlation_heatmap.png")
    print("     Done.")


def section_06_topfeatures_fraud_vs_legit(df, fh):
    """
    ### EDA Section 6 — Top-4 Feature Distributions: Fraud vs Legitimate
    What: Side-by-side KDE plots for the 4 most correlated features.
    Why : Seeing *how* a feature separates fraud from legitimate transactions
          validates its discriminative power and informs thresholding decisions.
    """
    print("\n[EDA 6/7] Top feature distributions (fraud vs legit)...")

    num_df  = df.select_dtypes(include="number")
    corr    = num_df.corr()["isFraud"].drop("isFraud").abs().sort_values(ascending=False)
    top4    = [c for c in corr.head(10).index if c not in ("TransactionID", "TransactionDT")][:4]

    if not top4:
        print("     Skipped — insufficient numeric features.")
        return

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes      = axes.flatten()
    fig.suptitle("Top Feature Distributions — Fraud vs Legitimate", fontsize=16)

    for ax, col in zip(axes, top4):
        legit = df.loc[df["isFraud"] == 0, col].dropna()
        fraud = df.loc[df["isFraud"] == 1, col].dropna()
        p01, p99 = df[col].quantile([0.01, 0.99])
        legit = legit.clip(p01, p99)
        fraud = fraud.clip(p01, p99)

        sns.kdeplot(legit, ax=ax, color=LEGIT_CLR, label="Legitimate",
                    fill=True, alpha=0.30, linewidth=2)
        sns.kdeplot(fraud, ax=ax, color=FRAUD_CLR, label="Fraudulent",
                    fill=True, alpha=0.55, linewidth=2)
        ax.set_title(col, fontsize=11)
        ax.set_xlabel("")
        ax.legend(fontsize=9)

    fig.tight_layout()
    _save(fig, "06_topfeature_distributions.png")
    print("     Done.")


def section_07_fraud_amount_buckets(df, fh):
    """
    ### EDA Section 7 — Fraud Rate by Transaction Amount Bucket
    What: Bin TransactionAmt into ranges and compute fraud rate per bin.
    Why : Fraud is not uniformly distributed across amounts. Micro-transactions
          (card testing) and extremely high-value transactions are known fraud
          hotspots. This plot makes that visible.
    """
    print("\n[EDA 7/7] Fraud rate by amount bucket...")

    bins   = [0, 10, 50, 100, 250, 500, 1000, 5000, float("inf")]
    labels = ["<$10", "$10-50", "$50-100", "$100-250",
              "$250-500", "$500-1K", "$1K-5K", ">$5K"]

    df2              = df[["TransactionAmt", "isFraud"]].dropna().copy()
    df2["AmtBucket"] = pd.cut(df2["TransactionAmt"], bins=bins, labels=labels)
    bucket_stats     = (
        df2.groupby("AmtBucket", observed=True)["isFraud"]
        .agg(["mean", "count"])
        .rename(columns={"mean": "fraud_rate", "count": "n"})
        .reset_index()
    )

    lines = ["Fraud rate by transaction amount bucket:"]
    for _, row in bucket_stats.iterrows():
        lines.append(
            f"  {str(row['AmtBucket']):<12}  "
            f"fraud rate = {row['fraud_rate']*100:5.2f}%   n = {int(row['n']):,}"
        )
    _section("7. Fraud Rate by Transaction Amount", lines, fh)

    fig, ax1 = plt.subplots(figsize=(13, 5))
    fig.suptitle("Fraud Rate & Volume by Transaction Amount Bucket", fontsize=15)

    x = range(len(bucket_stats))
    ax2 = ax1.twinx()
    ax2.bar(x, bucket_stats["n"], color=LEGIT_CLR, alpha=0.25, label="# Transactions")
    ax2.set_ylabel("Transaction Count", color=LEGIT_CLR)
    ax2.tick_params(axis="y", colors=LEGIT_CLR)
    ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{int(v):,}"))

    ax1.plot(x, bucket_stats["fraud_rate"] * 100, color=FRAUD_CLR,
             marker="o", linewidth=2.5, markersize=8, label="Fraud Rate %", zorder=5)
    ax1.set_ylabel("Fraud Rate (%)", color=FRAUD_CLR)
    ax1.tick_params(axis="y", colors=FRAUD_CLR)
    ax1.set_xticks(list(x))
    ax1.set_xticklabels(bucket_stats["AmtBucket"].astype(str), rotation=20, ha="right")
    ax1.set_xlabel("Transaction Amount Bucket")
    ax1.axhline(df["isFraud"].mean() * 100, color=ACCENT_CLR,
                linestyle="--", linewidth=1.2, label="Overall fraud rate", zorder=4)

    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, labels1 + labels2, loc="upper right")

    fig.tight_layout()
    _save(fig, "07_fraud_by_amount_bucket.png")
    print("     Done.")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────
def main():
    print("=" * 60)
    print("  IEEE-CIS Fraud Detection — EDA Engine")
    print("=" * 60)

    # ── Load ──────────────────────────────────────────────────────────────────
    if not os.path.exists(DATA_PATH):
        print(f"\n❌  Preprocessed CSV not found at:\n    {DATA_PATH}")
        print("   Run  python3 src/preprocessing.py  first.")
        sys.exit(1)

    print(f"\nLoading {os.path.relpath(DATA_PATH, BASE_DIR)} ...")
    df = pd.read_csv(DATA_PATH)
    print(f"Loaded  {df.shape[0]:,} rows × {df.shape[1]:,} columns\n")

    # ── Open report file ─────────────────────────────────────────────────────
    with open(REPORT_PATH, "w") as fh:
        fh.write("IEEE-CIS Fraud Detection — EDA Summary Report\n")
        fh.write("=" * 72 + "\n")
        fh.write(f"Dataset : {os.path.relpath(DATA_PATH, BASE_DIR)}\n")
        fh.write(f"Rows    : {df.shape[0]:,}\n")
        fh.write(f"Columns : {df.shape[1]:,}\n")

        section_01_overview(df, fh)
        section_02_class_imbalance(df, fh)
        section_03_transaction_amount(df, fh)
        section_04_temporal_patterns(df, fh)
        section_05_correlation_heatmap(df, fh)
        section_06_topfeatures_fraud_vs_legit(df, fh)
        section_07_fraud_amount_buckets(df, fh)

    print(f"\n✅  EDA complete!")
    print(f"   Figures → {os.path.relpath(FIG_DIR,  BASE_DIR)}/")
    print(f"   Report  → {os.path.relpath(REPORT_PATH, BASE_DIR)}")
    print("=" * 60)


if __name__ == "__main__":
    main()